spring.application.name=app
spring.mongodb.uri=mongodb://banktracker:banktracker@localhost:27017/banktracker?authSource=admin
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.profiles.active=prod