services:
  mongodb:
    image: 'mongo:latest'
    container_name: banktracker-db
    environment:
      - 'MONGO_INITDB_DATABASE=banktracker'
      - 'MONGO_INITDB_ROOT_PASSWORD=banktracker'
      - 'MONGO_INITDB_ROOT_USERNAME=banktracker'
    ports:
      - '27017:27017'